export const GASTOS_MES = 'GASTOS_MES';
export const FORMULARIO_MES = 'FORMULARIO_MES'
export const AGREGAR_MES = 'AGREGAR_MES'
export const MES_ACTUAL = 'MES_ACTUAL';

export const OBTENER_GASTO = 'OBTENER_GASTO'
export const MOSTRAR_FORM_GASTO = 'MOSTRAR_FORM_GASTO'
export const AGREGAR_GASTO = 'AGREGAR_GASTO'
export const ELIMINAR_GASTO = 'ELIMINAR_GASTO'
export const EDITAR_GASTO = 'EDITAR_GASTO'
export const CAMBIAR_ESTADO_GASTO = 'CAMBIAR_ESTADO_GASTO'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

export const REGISTRO_EXISTOSO = 'REGISTRO_EXISTOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'


